samples:
  sample1: "data/sample1.fastq"
  sample2: "data/sample2.fastq"
  # Add all your samples here

indices:
  index1: "db/index1"
  index2: "db/index2"
  index3: "db/index3"
  index4: "db/index4"
  # Add all indices here

node_indices:
  node1:
    - "index1"
    - "index2"
  node2:
    - "index3"
    - "index4"
  # Add more nodes and their indices as necessary
